services:
  cockroachdb:
    image: cockroachdb/cockroach:latest-v23.1
    command: start-single-node --insecure --store=attrs=ram,path=/var/lib/cockroach/
    restart: "always"
    environment:
      - COCKROACH_DATABASE=nakama
      - COCKROACH_USER=root
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - data:/var/lib/cockroach

  nakama:
    image: heroiclabs/nakama:3.22.0
    environment:
      - CORS_ALLOW_ORIGIN=https://tictactoe-with-nakama.vercel.app
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - |
        /nakama/nakama migrate up --database.address root@cockroachdb:26257 && \
        exec /nakama/nakama \
          --name nakama1 \
          --database.address root@cockroachdb:26257 \
          --logger.level DEBUG \
          --session.token_expiry_sec 7200 \
          --metrics.prometheus_port 9100 \
          --runtime.path /nakama/data/modules \
          --runtime.js_entrypoint main.js \
          --socket.response_headers "Access-Control-Allow-Origin=$${CORS_ALLOW_ORIGIN}" \
          --socket.response_headers "Access-Control-Allow-Headers=Authorization,Content-Type" \
          --socket.response_headers "Access-Control-Allow-Methods=GET,POST,PUT,DELETE,OPTIONS" \
          "$$@"
    restart: "always"
    links:
      - "cockroachdb:db"
    depends_on:
      - cockroachdb
    volumes:
      - ./backend/data:/nakama/data
      - ./backend/build:/nakama/data/modules
    expose:
      - "7349"
      - "7350"
      - "7351"
      - "9100"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    healthcheck:
      test: ["CMD", "/nakama/nakama", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - nakama

volumes:
  data:
